// Daily-rotating "legacy" figures — a calm, motivational banner (not gamification).
// Real public-domain/CC portraits (Wikimedia) + themed scene backdrops (Unsplash),
// spanning science, art & literature, philosophy, music, sports, business & invention,
// activism & politics, exploration, mathematics, and film & performing arts.

const WM = (path: string) => "https://upload.wikimedia.org/" + path;
const WP = (n: string) =>
  "https://commons.wikimedia.org/wiki/Special:FilePath/" + encodeURIComponent(n) + "?width=600";
const UN = (id: string, w = 1200) =>
  "https://images.unsplash.com/photo-" + id + "?auto=format&fit=crop&w=" + w + "&q=72";

/** Reusable themed scene backdrops, shared across figures in the same field. */
const SCENES = {
  lab: { img: UN("1532094349884-543bc11b234d"), label: "a glowing laboratory bench" },
  workshop: { img: UN("1503694978374-8a2fa686963a"), label: "an inventor's cluttered workshop" },
  studio: { img: UN("1513364776144-60967b0f800f"), label: "a sunlit painter's studio" },
  forum: { img: UN("1552832230-c0197dd311b5"), label: "the Roman forum at dusk" },
  engine: { img: UN("1518770660439-4636190af475"), label: "an early brass computing engine" },
  lectern: { img: UN("1517457373958-b7bdd4587205"), label: "a crowded lecture hall mid-speech" },
  library: { img: UN("1758380743428-ac0b72817e94"), label: "a grand library of tall bookshelves" },
  mountain: { img: UN("1752503650851-cbc3f8b00679"), label: "a mountain ridge at sunrise" },
  ocean: { img: UN("1774031826492-3d859b950574"), label: "a tall ship on the open ocean" },
  temple: { img: UN("1754466176385-1f9db262d456"), label: "the quiet interior of an ancient temple" },
  concert: { img: UN("1761173084851-1e5302e931fe"), label: "an empty concert hall, golden and vast" },
  stadium: { img: UN("1659092375775-4e72014d7818"), label: "a sports stadium under the lights" },
  chalkboard: { img: UN("1758685734312-5134968399a8"), label: "a blackboard dense with formulas" },
  factory: { img: UN("1680372669297-f299308e437a"), label: "an old machine hall, gears and light" },
  curtain: { img: UN("1767811556101-d4dacddc8cb6"), label: "a red velvet stage curtain" },
  rally: { img: UN("1761001826423-7231bfe1ee37"), label: "a crowd gathered for a rally" },
  cosmos: { img: UN("1707587537206-14ad37434358"), label: "a dark sky filled with stars" },
} as const;

type SceneKey = keyof typeof SCENES;

export interface Figure {
  name: string;
  years: string;
  emoji: string;
  portrait: string;
  scene: string;
  sceneImg: string;
  /** True when sceneImg is a Wikimedia photo of a real place (not a generic Unsplash
   * stock scene) — these should skip Next's image optimizer like the portrait does,
   * for the same Wikimedia-rate-limit reason (see RemoteImage's `unoptimized`). */
  scenePersonal: boolean;
  quote: string;
  legacy: string;
}

interface RawFigure {
  name: string;
  years: string;
  emoji: string;
  portrait: string;
  scene: SceneKey;
  /** A real photo of a place tied to this person's life (birthplace, workplace, a landmark
   * tied to their achievement). Preferred over the generic field `scene` when present. */
  place?: string;
  placeCaption?: string;
  quote: string;
  legacy: string;
}

const RAW: RawFigure[] = [
  // ── Science ──────────────────────────────────────────────────────────
  { name: "Marie Curie", years: "1867–1934", emoji: "⚗️", scene: "lab", place: WM("wikipedia/commons/thumb/3/35/Aleja_Niepdleglosci_Warsaw_2022_aerial_%28cropped%29.jpg/1280px-Aleja_Niepdleglosci_Warsaw_2022_aerial_%28cropped%29.jpg"), placeCaption: "Warsaw — her birthplace",
    portrait: WP("Marie_Curie_c1920.jpg"),
    quote: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more.",
    legacy: "Pioneered radioactivity and became the first person ever to win two Nobel Prizes." },
  { name: "Albert Einstein", years: "1879–1955", emoji: "🧠", scene: "cosmos", place: WM("wikipedia/commons/thumb/8/8c/Ulm_Panorama_01.jpg/1280px-Ulm_Panorama_01.jpg"), placeCaption: "Ulm — his birthplace",
    portrait: WM("wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/960px-Albert_Einstein_Head_cleaned.jpg"),
    quote: "Imagination is more important than knowledge.",
    legacy: "Reshaped physics with the theory of relativity and reimagined space, time, and gravity." },
  { name: "Isaac Newton", years: "1642–1727", emoji: "🍎", scene: "lab", place: WM("wikipedia/commons/thumb/e/e8/LEO3122_2022_04_0002.jpg/1280px-LEO3122_2022_04_0002.jpg"), placeCaption: "Woolsthorpe Manor — his birthplace and the apple-tree orchard",
    portrait: WM("wikipedia/commons/thumb/f/f7/Portrait_of_Sir_Isaac_Newton%2C_1689_%28brightened%29.jpg/960px-Portrait_of_Sir_Isaac_Newton%2C_1689_%28brightened%29.jpg"),
    quote: "If I have seen further it is by standing on the shoulders of Giants.",
    legacy: "Laid the foundations of classical mechanics and invented calculus." },
  { name: "Charles Darwin", years: "1809–1882", emoji: "🐢", scene: "lab", place: WM("wikipedia/commons/6/6d/Down_House.jpg"), placeCaption: "Down House — where he wrote On the Origin of Species",
    portrait: WM("wikipedia/commons/thumb/2/2e/Charles_Darwin_seated_crop.jpg/960px-Charles_Darwin_seated_crop.jpg"),
    quote: "There is grandeur in this view of life… endless forms most beautiful and most wonderful have been, and are being, evolved.",
    legacy: "Proposed natural selection, transforming how we understand the origin of species." },
  { name: "Nikola Tesla", years: "1856–1943", emoji: "⚡", scene: "lab", place: WM("wikipedia/commons/thumb/a/ab/3Falls_Niagara.jpg/1280px-3Falls_Niagara.jpg"), placeCaption: "Niagara Falls — site of his first AC power plant",
    portrait: WM("wikipedia/commons/7/79/Tesla_circa_1890.jpeg"),
    quote: "The present is theirs; the future, for which I really worked, is mine.",
    legacy: "Pioneered alternating-current power and held over 300 patents in his lifetime." },
  { name: "Rosalind Franklin", years: "1920–1958", emoji: "🧬", scene: "lab", place: WM("wikipedia/commons/thumb/4/41/King%27s_College%2C_London_full_achievement.svg/1280px-King%27s_College%2C_London_full_achievement.svg.png"), placeCaption: "King's College London — where she X-rayed DNA",
    portrait: WM("wikipedia/commons/f/fd/Rosalind_Franklin_%28retouched%29.jpg"),
    quote: "Science and everyday life cannot and should not be separated.",
    legacy: "Her X-ray images were pivotal to discovering the structure of DNA." },
  { name: "Louis Pasteur", years: "1822–1895", emoji: "🔬", scene: "lab", place: WM("wikipedia/commons/thumb/d/dd/Centre-medical-de-l%27institute-pasteur.jpg/1280px-Centre-medical-de-l%27institute-pasteur.jpg"), placeCaption: "Institut Pasteur, Paris — the institute he founded",
    portrait: WM("wikipedia/commons/thumb/a/a6/Louis_Pasteur%2C_foto_av_Paul_Nadar%2C_Crisco_edit.jpg/960px-Louis_Pasteur%2C_foto_av_Paul_Nadar%2C_Crisco_edit.jpg"),
    quote: "Chance favors the prepared mind.",
    legacy: "Developed pasteurization and germ theory, saving millions of lives." },
  { name: "Michael Faraday", years: "1791–1867", emoji: "🔌", scene: "lab", place: WM("wikipedia/en/2/2d/Royal_Institution_logo.png"), placeCaption: "The Royal Institution, London — where he worked and lectured",
    portrait: WM("wikipedia/commons/thumb/7/7e/Michael_Faraday_sitting_crop.jpg/960px-Michael_Faraday_sitting_crop.jpg"),
    quote: "Nothing is too wonderful to be true if it be consistent with the laws of nature.",
    legacy: "Discovered electromagnetic induction, laying the groundwork for the electric motor." },
  { name: "Stephen Hawking", years: "1942–2018", emoji: "🌌", scene: "cosmos", place: WM("wikipedia/commons/thumb/c/c3/Coat_of_Arms_of_the_University_of_Cambridge.svg/1280px-Coat_of_Arms_of_the_University_of_Cambridge.svg.png"), placeCaption: "University of Cambridge — where he spent his career",
    portrait: WM("wikipedia/commons/e/eb/Stephen_Hawking.StarChild.jpg"),
    quote: "However difficult life may seem, there is always something you can do and succeed at.",
    legacy: "Explained the physics of black holes despite decades living with ALS." },
  { name: "Carl Sagan", years: "1934–1996", emoji: "🔭", scene: "cosmos", place: WM("wikipedia/commons/thumb/4/47/Cornell_University_seal.svg/1280px-Cornell_University_seal.svg.png"), placeCaption: "Cornell University — where he taught and wrote Cosmos",
    portrait: WM("wikipedia/commons/b/be/Carl_Sagan_Planetary_Society.JPG"),
    quote: "Somewhere, something incredible is waiting to be known.",
    legacy: "Brought the wonder of the cosmos to millions through Cosmos and his writing." },
  { name: "Galileo Galilei", years: "1564–1642", emoji: "🔭", scene: "cosmos", place: WM("wikipedia/commons/thumb/d/d3/Italy_-_Pisa.jpg/1280px-Italy_-_Pisa.jpg"), placeCaption: "Pisa — his birthplace, beside the Leaning Tower",
    portrait: WM("wikipedia/commons/thumb/f/fc/Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff/lossy-page1-960px-Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff.jpg"),
    quote: "All truths are easy to understand once they are discovered; the point is to discover them.",
    legacy: "Turned a telescope to the heavens and gave the Copernican model its proof." },
  { name: "Johannes Kepler", years: "1571–1630", emoji: "🪐", scene: "cosmos", place: WM("wikipedia/commons/0/04/WdSt-PeterundPaul.jpg"), placeCaption: "Weil der Stadt — his birthplace",
    portrait: WM("wikipedia/commons/7/74/JKepler.jpg"),
    quote: "Nature uses as little as possible of anything.",
    legacy: "Derived the laws of planetary motion that later underpinned Newton's gravity." },
  { name: "Rachel Carson", years: "1907–1964", emoji: "🌿", scene: "lab", place: WM("wikipedia/commons/thumb/c/c6/Marine_Biological_Laboratory%2C_Woods_Hole_by_Pam_Wilmot.jpg/1280px-Marine_Biological_Laboratory%2C_Woods_Hole_by_Pam_Wilmot.jpg"), placeCaption: "Woods Hole — the marine research town that shaped her writing",
    portrait: WM("wikipedia/commons/thumb/f/f4/Rachel-Carson.jpg/960px-Rachel-Carson.jpg"),
    quote: "In nature nothing exists alone.",
    legacy: "Silent Spring sparked the modern environmental movement." },
  { name: "Alexander Fleming", years: "1881–1955", emoji: "💊", scene: "lab", place: WM("wikipedia/commons/thumb/e/e1/St_Mary%27s_Hospital.jpg/1280px-St_Mary%27s_Hospital.jpg"), placeCaption: "St Mary's Hospital, London — where he discovered penicillin",
    portrait: WM("wikipedia/commons/thumb/b/bf/Synthetic_Production_of_Penicillin_TR1468.jpg/960px-Synthetic_Production_of_Penicillin_TR1468.jpg"),
    quote: "One sometimes finds what one is not looking for.",
    legacy: "His discovery of penicillin launched the age of antibiotics." },
  { name: "Jane Goodall", years: "1934–", emoji: "🐒", scene: "mountain", place: WM("wikipedia/commons/thumb/a/a2/Gombe_Stream_NP_Mutter_und_Kind.jpg/1280px-Gombe_Stream_NP_Mutter_und_Kind.jpg"), placeCaption: "Gombe Stream National Park — where she studied wild chimpanzees",
    portrait: WM("wikipedia/commons/9/98/Deputy_Secretary_Higginbottom_Poses_for_a_Photo_With_Dr._Jane_Goodall_and_the_State_Department%27s_Global_Health_Diplomacy_Director_Jordan_in_Washington_%2822365513310%29_%282%29_%28cropped_2%29.jpg"),
    quote: "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    legacy: "Redefined primatology by living among and studying wild chimpanzees." },
  { name: "Richard Feynman", years: "1918–1988", emoji: "🧪", scene: "chalkboard",
    portrait: WM("wikipedia/en/4/42/Richard_Feynman_Nobel.jpg"),
    quote: "I would rather have questions that can't be answered than answers that can't be questioned.",
    legacy: "A Nobel physicist whose lectures made quantum mechanics vivid and human." },

  // ── Art & literature ─────────────────────────────────────────────────
  { name: "Leonardo da Vinci", years: "1452–1519", emoji: "🎨", scene: "workshop", place: WM("wikipedia/commons/thumb/5/54/VinciPanorama3.jpg/1280px-VinciPanorama3.jpg"), placeCaption: "Vinci, Italy — the town of his birth",
    portrait: WP("Leonardo_self.jpg"),
    quote: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them.",
    legacy: "Painter, engineer and anatomist whose notebooks anticipated inventions by centuries." },
  { name: "Vincent van Gogh", years: "1853–1890", emoji: "🌻", scene: "studio", place: WM("wikipedia/commons/thumb/3/3c/1_arles_france_2016.jpg/1280px-1_arles_france_2016.jpg"), placeCaption: "Arles, France — where he painted many of his best-known works",
    portrait: WP("Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_(454045).jpg"),
    quote: "Great things are not done by impulse, but by a series of small things brought together.",
    legacy: "Made nearly 900 paintings in a single decade and reshaped the course of modern art." },
  { name: "William Shakespeare", years: "1564–1616", emoji: "🎭", scene: "curtain", place: WM("wikipedia/commons/thumb/5/5e/Stratford-Upon-Avon%2C_High_Street%2C_geograph_3969622_by_Lewis_Clarke.jpg/1280px-Stratford-Upon-Avon%2C_High_Street%2C_geograph_3969622_by_Lewis_Clarke.jpg"), placeCaption: "Stratford-upon-Avon — his birthplace",
    portrait: WM("wikipedia/commons/thumb/2/21/William_Shakespeare_by_John_Taylor%2C_edited.jpg/960px-William_Shakespeare_by_John_Taylor%2C_edited.jpg"),
    quote: "We know what we are, but know not what we may be.",
    legacy: "His plays and sonnets reshaped the English language itself." },
  { name: "Jane Austen", years: "1775–1817", emoji: "📚", scene: "library", place: WM("wikipedia/commons/e/e4/Jane_Austen%27s_House%2C_Chawton_-_geograph.org.uk_-_946021.jpg"), placeCaption: "Jane Austen's House, Chawton — where she wrote and revised her novels",
    portrait: WM("wikipedia/commons/thumb/c/cc/CassandraAusten-JaneAusten%28c.1810%29_hires.jpg/960px-CassandraAusten-JaneAusten%28c.1810%29_hires.jpg"),
    quote: "I declare after all there is no enjoyment like reading!",
    legacy: "Her novels of wit and social insight remain touchstones of the English canon." },
  { name: "Mark Twain", years: "1835–1910", emoji: "🖋️", scene: "library", place: WM("wikipedia/commons/thumb/9/93/Mark_Twain_Boyhood_Home_1.jpg/1280px-Mark_Twain_Boyhood_Home_1.jpg"), placeCaption: "Hannibal, Missouri — his boyhood hometown",
    portrait: WM("wikipedia/commons/7/7a/Mark_Twain_by_AF_Bradley_%28cropped_2%29.jpg"),
    quote: "It is curious that physical courage should be so common in the world and moral courage so rare.",
    legacy: "America's great satirist, from riverboat pilot to literary icon." },
  { name: "Virginia Woolf", years: "1882–1941", emoji: "🖋️", scene: "library", place: WM("wikipedia/commons/thumb/1/1b/British_Museum_from_NE_2_%28cropped%29.JPG/1280px-British_Museum_from_NE_2_%28cropped%29.JPG"), placeCaption: "Bloomsbury, London — home of the literary circle she led",
    portrait: WM("wikipedia/commons/thumb/0/0b/George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg/960px-George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg"),
    quote: "A woman must have money and a room of her own if she is to write fiction.",
    legacy: "Pioneered stream-of-consciousness narrative and modern feminist thought." },
  { name: "Toni Morrison", years: "1931–2019", emoji: "📖", scene: "library", place: WM("wikipedia/commons/thumb/e/eb/Lorain%2C_Ohio_Skyline.jpg/1280px-Lorain%2C_Ohio_Skyline.jpg"), placeCaption: "Lorain, Ohio — her birthplace",
    portrait: WM("wikipedia/commons/thumb/3/3a/Toni_Morrison.jpg/960px-Toni_Morrison.jpg"),
    quote: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.",
    legacy: "The first Black woman to win the Nobel Prize in Literature." },
  { name: "Pablo Picasso", years: "1881–1973", emoji: "🎨", scene: "studio", place: WM("wikipedia/commons/thumb/9/94/Da_Gibralfaro_%28cropped%292.jpg/1280px-Da_Gibralfaro_%28cropped%292.jpg"), placeCaption: "Málaga, Spain — his birthplace",
    portrait: WM("wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/960px-Pablo_picasso_1.jpg"),
    quote: "Art is the elimination of the unnecessary.",
    legacy: "Co-founded Cubism and reinvented painting and sculpture across seven decades." },
  { name: "Frida Kahlo", years: "1907–1954", emoji: "🎨", scene: "studio", place: WM("wikipedia/commons/thumb/4/4c/Museo_Frida_Kahlo.JPG/1280px-Museo_Frida_Kahlo.JPG"), placeCaption: "La Casa Azul, Mexico City — her lifelong home",
    portrait: WM("wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg/960px-Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg"),
    quote: "I paint my own reality.",
    legacy: "Turned personal pain into some of the 20th century's most iconic self-portraits." },
  { name: "Maya Angelou", years: "1928–2014", emoji: "🕊️", scene: "library", place: WM("wikipedia/commons/thumb/9/9d/Lafayette_County_Arkansas_Incorporated_and_Unincorporated_areas_Stamps_Highlighted_0566320.svg/1280px-Lafayette_County_Arkansas_Incorporated_and_Unincorporated_areas_Stamps_Highlighted_0566320.svg.png"), placeCaption: "Stamps, Arkansas — her childhood hometown",
    portrait: WM("wikipedia/commons/thumb/4/4f/Angelou_at_Clinton_inauguration_%28cropped_2%29.jpg/960px-Angelou_at_Clinton_inauguration_%28cropped_2%29.jpg"),
    quote: "There is no greater agony than bearing an untold story inside you.",
    legacy: "Poet and memoirist whose voice became a touchstone of resilience." },
  { name: "Ernest Hemingway", years: "1899–1961", emoji: "🖋️", scene: "library", place: WM("wikipedia/commons/thumb/3/37/Southernmost_point_buoy%2C_NE_view.jpg/1280px-Southernmost_point_buoy%2C_NE_view.jpg"), placeCaption: "Key West, Florida — where he wrote many of his novels",
    portrait: WM("wikipedia/commons/thumb/2/28/ErnestHemingway.jpg/960px-ErnestHemingway.jpg"),
    quote: "The world breaks everyone, and afterward many are strong at the broken places.",
    legacy: "Stripped prose to its essentials and reshaped 20th-century fiction." },
  { name: "Emily Dickinson", years: "1830–1886", emoji: "🌸", scene: "library", place: WM("wikipedia/commons/thumb/4/41/Emily_Dickinson_Museum%2C_Amherst%2C_MA_-_front.JPG/1280px-Emily_Dickinson_Museum%2C_Amherst%2C_MA_-_front.JPG"), placeCaption: "The Homestead, Amherst — where she wrote nearly all her poems",
    portrait: WM("wikipedia/commons/thumb/5/56/Black-white_photograph_of_Emily_Dickinson2.png/960px-Black-white_photograph_of_Emily_Dickinson2.png"),
    quote: "Dwell in possibility.",
    legacy: "Wrote nearly 1,800 poems in near-seclusion, published almost entirely after her death." },
  { name: "Leo Tolstoy", years: "1828–1910", emoji: "📖", scene: "library", place: WM("wikipedia/commons/thumb/8/80/Tula_YasnayaPolyana_asv2019-09_img09_aerial_view_%28cropped%29.jpg/1280px-Tula_YasnayaPolyana_asv2019-09_img09_aerial_view_%28cropped%29.jpg"), placeCaption: "Yasnaya Polyana — his estate, where he wrote War and Peace",
    portrait: WM("wikipedia/commons/thumb/b/be/Leo_Tolstoy_1908_Portrait_%283x4_cropped%29.jpg/960px-Leo_Tolstoy_1908_Portrait_%283x4_cropped%29.jpg"),
    quote: "Everyone thinks of changing the world, but no one thinks of changing himself.",
    legacy: "War and Peace and Anna Karenina remain pillars of world literature." },
  { name: "Georgia O'Keeffe", years: "1887–1986", emoji: "🌼", scene: "studio", place: WM("wikipedia/commons/4/4e/Ghost_Ranch_redrock_cliffs.jpg"), placeCaption: "Ghost Ranch, New Mexico — the desert landscape she painted for decades",
    portrait: WM("wikipedia/commons/thumb/a/a2/Georgia_O%27Keeffe_MET_DP230868.jpg/960px-Georgia_O%27Keeffe_MET_DP230868.jpg"),
    quote: "I found I could say things with color and shapes that I couldn't say any other way.",
    legacy: "Her large-scale flowers and desert landscapes defined American modernism." },
  { name: "Rumi", years: "1207–1273", emoji: "🌙", scene: "temple", place: WM("wikipedia/commons/0/0a/Konyaaltincarsi.jpg"), placeCaption: "Konya, Turkey — home of his shrine and tomb",
    portrait: WM("wikipedia/commons/e/ea/%D9%85%D9%88%D9%84%D8%A7%D9%86%D8%A7_%D8%A7%D8%AB%D8%B1_%D8%AD%D8%B3%DB%8C%D9%86_%D8%A8%D9%87%D8%B2%D8%A7%D8%AF_%28cropped%29.jpg"),
    quote: "The wound is the place where the Light enters you.",
    legacy: "A 13th-century poet-mystic whose verses on love remain read worldwide." },
  { name: "Chinua Achebe", years: "1930–2013", emoji: "📚", scene: "library",
    portrait: WM("wikipedia/commons/thumb/e/e3/Chinua_Achebe%2C_1966.jpg/960px-Chinua_Achebe%2C_1966.jpg"),
    quote: "Until the lions have their own historians, the history of the hunt will always glorify the hunter.",
    legacy: "Things Fall Apart made him a founding voice of African literature." },

  // ── Philosophy ───────────────────────────────────────────────────────
  { name: "Marcus Aurelius", years: "121–180", emoji: "🏛️", scene: "forum", place: WM("wikipedia/commons/thumb/6/6a/Foro_Romano_Musei_Capitolini_Roma.jpg/1280px-Foro_Romano_Musei_Capitolini_Roma.jpg"), placeCaption: "the Roman Forum at dusk",
    portrait: WP("Marcus_Aurelius_Glyptothek_Munich.jpg"),
    quote: "The impediment to action advances action. What stands in the way becomes the way.",
    legacy: "A Roman emperor whose private journal became the Stoic classic, Meditations." },
  { name: "Socrates", years: "c.470–399 BC", emoji: "🏛️", scene: "forum", place: WM("wikipedia/commons/thumb/2/2c/1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg/1280px-1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg"), placeCaption: "the Acropolis of Athens, heart of the city he questioned",
    portrait: WM("wikipedia/commons/thumb/a/a4/Socrates_Louvre.jpg/960px-Socrates_Louvre.jpg"),
    quote: "The unexamined life is not worth living.",
    legacy: "Through Plato's dialogues, his method of questioning founded Western philosophy." },
  { name: "Confucius", years: "551–479 BC", emoji: "🎋", scene: "temple", place: WM("wikipedia/commons/thumb/a/a5/Qufu_Zhougong_Miao_2015.08.16_07-56-33.jpg/1280px-Qufu_Zhougong_Miao_2015.08.16_07-56-33.jpg"), placeCaption: "Qufu — his hometown and the Temple of Confucius",
    portrait: WM("wikipedia/commons/5/54/Confucius_Tang_Dynasty.jpg"),
    quote: "Our greatest glory is not in never falling, but in rising every time we fall.",
    legacy: "His teachings on ethics and order shaped East Asian thought for millennia." },
  { name: "Lao Tzu", years: "c.6th century BC", emoji: "☯️", scene: "temple",
    portrait: WM("wikipedia/commons/thumb/9/91/Laozi_%28Chinese_characters%29.svg/960px-Laozi_%28Chinese_characters%29.svg.png"),
    quote: "A journey of a thousand miles begins with a single step.",
    legacy: "Traditionally credited as the author of the Tao Te Ching, the root text of Taoism." },
  { name: "Immanuel Kant", years: "1724–1804", emoji: "📘", scene: "library", place: WM("wikipedia/commons/thumb/b/ba/K%C3%B6nigsberg_Castle.jpg/1280px-K%C3%B6nigsberg_Castle.jpg"), placeCaption: "Königsberg — the city he never left",
    portrait: WM("wikipedia/commons/thumb/7/79/Immanuel_Kant_-_Gemaelde_1.jpg/960px-Immanuel_Kant_-_Gemaelde_1.jpg"),
    quote: "Act only according to that maxim whereby you can at the same time will that it should become a universal law.",
    legacy: "His Critique of Pure Reason reshaped modern philosophy's account of knowledge." },
  { name: "Friedrich Nietzsche", years: "1844–1900", emoji: "⛰️", scene: "mountain", place: WM("wikipedia/commons/thumb/f/f5/Weimar_stadtschloss_front_2025.jpg/1280px-Weimar_stadtschloss_front_2025.jpg"), placeCaption: "Weimar — where he spent his final years",
    portrait: WM("wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/960px-Nietzsche187a.jpg"),
    quote: "He who has a why to live can bear almost any how.",
    legacy: "Challenged conventional morality and questioned the foundations of truth itself." },
  { name: "Simone de Beauvoir", years: "1908–1986", emoji: "📗", scene: "library", place: WM("wikipedia/commons/thumb/6/69/Caf%C3%A9_de_Flore%2C_172_boulevard_Saint-Germain%2C_Paris_6e.jpg/1280px-Caf%C3%A9_de_Flore%2C_172_boulevard_Saint-Germain%2C_Paris_6e.jpg"), placeCaption: "Café de Flore, Paris — where she wrote for hours each day",
    portrait: WM("wikipedia/commons/5/55/Simone_De_Beauvoir_%28cropped%29.jpg"),
    quote: "One is not born, but rather becomes, a woman.",
    legacy: "The Second Sex became a founding text of modern feminist philosophy." },
  { name: "Hannah Arendt", years: "1906–1975", emoji: "📕", scene: "library", place: WM("wikipedia/commons/thumb/d/dd/The_New_School_seal.svg/1280px-The_New_School_seal.svg.png"), placeCaption: "The New School, New York — where she taught for two decades",
    portrait: WM("wikipedia/commons/thumb/c/cd/Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg/960px-Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg"),
    quote: "The sad truth is that most evil is done by people who never made up their minds to be good or evil.",
    legacy: "Her writing on totalitarianism reshaped 20th-century political thought." },
  { name: "The Buddha", years: "c.563–483 BC", emoji: "🪷", scene: "temple", place: WM("wikipedia/commons/thumb/4/4e/Mahabodhitemple.jpg/1280px-Mahabodhitemple.jpg"), placeCaption: "the Mahabodhi Temple, Bodh Gaya — site of his enlightenment",
    portrait: WM("wikipedia/commons/thumb/f/ff/Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg/960px-Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg"),
    quote: "Peace comes from within. Do not seek it without.",
    legacy: "His teachings on suffering and awakening founded Buddhism." },
  { name: "Epictetus", years: "c.50–135", emoji: "🏛️", scene: "forum", place: WM("wikipedia/commons/1/1f/Nicopolis_nymphaeum.jpg"), placeCaption: "Nicopolis — where he ran his school of philosophy",
    portrait: WM("wikipedia/commons/thumb/c/c0/Epicteti_Enchiridion_Latinis_versibus_adumbratum_%28Oxford_1715%29_frontispiece_%28cropped%29.jpg/960px-Epicteti_Enchiridion_Latinis_versibus_adumbratum_%28Oxford_1715%29_frontispiece_%28cropped%29.jpg"),
    quote: "It's not what happens to you, but how you react to it that matters.",
    legacy: "A former slave whose Stoic teachings still shape modern resilience thinking." },
  { name: "René Descartes", years: "1596–1650", emoji: "📐", scene: "library", place: WM("wikipedia/commons/thumb/2/2e/H%C3%B4tel_de_Ville_LA_HAYE-DESCARTES_-_Jean-Charles_GUILLO.jpg/1280px-H%C3%B4tel_de_Ville_LA_HAYE-DESCARTES_-_Jean-Charles_GUILLO.jpg"), placeCaption: "Descartes, France — his birthplace, later renamed for him",
    portrait: WM("wikipedia/commons/7/73/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg"),
    quote: "I think, therefore I am.",
    legacy: "Cogito ergo sum made him a founder of modern Western philosophy." },
  { name: "John Stuart Mill", years: "1806–1873", emoji: "📘", scene: "library", place: WM("wikipedia/commons/thumb/6/67/London_Skyline_%28125508655%29.jpeg/1280px-London_Skyline_%28125508655%29.jpeg"), placeCaption: "London — where he lived and wrote On Liberty",
    portrait: WM("wikipedia/commons/thumb/9/99/John_Stuart_Mill_by_London_Stereoscopic_Company%2C_c1870.jpg/960px-John_Stuart_Mill_by_London_Stereoscopic_Company%2C_c1870.jpg"),
    quote: "The only freedom which deserves the name is that of pursuing our own good in our own way.",
    legacy: "On Liberty remains a foundational text of modern liberal thought." },
  { name: "Baruch Spinoza", years: "1632–1677", emoji: "📗", scene: "library", place: WM("wikipedia/commons/thumb/5/57/Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png/1280px-Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png"), placeCaption: "Amsterdam — his birthplace",
    portrait: WM("wikipedia/commons/thumb/e/ea/Spinoza.jpg/960px-Spinoza.jpg"),
    quote: "The highest activity a human being can attain is learning for understanding, because to understand is to be free.",
    legacy: "Argued for reason and tolerance at great personal cost in 17th-century Europe." },
  { name: "Thích Nhất Hạnh", years: "1926–2022", emoji: "🪷", scene: "temple",
    portrait: WM("wikipedia/commons/8/82/%E4%B8%80%E8%A1%8C%E7%A6%AA%E5%B8%AB_%E8%B6%8A%E5%8D%97%E4%BD%9B%E6%95%99%E8%87%A8%E6%BF%9F%E5%AE%97%E7%AC%AC%E5%9B%9B%E5%8D%81%E4%BA%8C%E4%BB%A3%E6%B3%95%E5%97%A3.jpg"),
    quote: "The present moment is the only moment available to us, and it is the door to all moments.",
    legacy: "A Vietnamese monk who brought mindfulness practice to the modern West." },

  // ── Music ────────────────────────────────────────────────────────────
  { name: "Ludwig van Beethoven", years: "1770–1827", emoji: "🎼", scene: "concert", place: WM("wikipedia/commons/thumb/9/99/General_view_over_bonn_%28cropped%29.jpg/1280px-General_view_over_bonn_%28cropped%29.jpg"), placeCaption: "Bonn — his birthplace",
    portrait: WM("wikipedia/commons/thumb/6/6e/Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg/960px-Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg"),
    quote: "To play a wrong note is insignificant; to play without passion is inexcusable.",
    legacy: "Composed some of his greatest works, including the 9th Symphony, after losing his hearing." },
  { name: "Wolfgang Amadeus Mozart", years: "1756–1791", emoji: "🎹", scene: "concert", place: WM("wikipedia/commons/thumb/9/91/Salzburg_%2848489551981%29.jpg/1280px-Salzburg_%2848489551981%29.jpg"), placeCaption: "Salzburg — his birthplace",
    portrait: WM("wikipedia/commons/thumb/a/ad/The_Mozart_Family_-_Wolfgang_Amadeus_Mozart_headshot.jpg/960px-The_Mozart_Family_-_Wolfgang_Amadeus_Mozart_headshot.jpg"),
    quote: "Neither a lofty degree of intelligence nor imagination… are essential to genius. Love, love, love, that is the soul of genius.",
    legacy: "A child prodigy who composed over 600 works before his death at 35." },
  { name: "Johann Sebastian Bach", years: "1685–1750", emoji: "🎻", scene: "concert", place: WM("wikipedia/commons/3/36/Leipzig_Thomaskirche.jpg"), placeCaption: "St. Thomas Church, Leipzig — where he was choirmaster for 27 years",
    portrait: WM("wikipedia/commons/thumb/6/6a/Johann_Sebastian_Bach.jpg/960px-Johann_Sebastian_Bach.jpg"),
    quote: "It is the special province of music to move the heart.",
    legacy: "His fugues and cantatas became the bedrock of Western classical composition." },
  { name: "Louis Armstrong", years: "1901–1971", emoji: "🎺", scene: "concert", place: WM("wikipedia/commons/thumb/c/cb/New_Orleans_from_the_Air_September_2019_-_Central_Business_District_Skyline_%28cropped%29.jpg/1280px-New_Orleans_from_the_Air_September_2019_-_Central_Business_District_Skyline_%28cropped%29.jpg"), placeCaption: "New Orleans — birthplace of jazz, and of Armstrong himself",
    portrait: WM("wikipedia/commons/thumb/1/16/Louis_Armstrong_in_Color_%28restored%29.jpg/960px-Louis_Armstrong_in_Color_%28restored%29.jpg"),
    quote: "What we play is life.",
    legacy: "His trumpet and voice helped invent jazz as a global art form." },
  { name: "Nina Simone", years: "1933–2003", emoji: "🎹", scene: "concert", place: WM("wikipedia/commons/7/74/Trade_st_2.jpg"), placeCaption: "Tryon, North Carolina — her birthplace",
    portrait: WM("wikipedia/commons/thumb/8/89/Nina_Simone_-1969.jpg/960px-Nina_Simone_-1969.jpg"),
    quote: "I'll tell you what freedom is to me: no fear.",
    legacy: "Fused classical training, jazz, and civil-rights conviction into a singular voice." },
  { name: "Bob Marley", years: "1945–1981", emoji: "🎸", scene: "concert", place: WM("wikipedia/commons/thumb/1/1f/Nine_Mile_-_the_neighbourhood.jpg/1280px-Nine_Mile_-_the_neighbourhood.jpg"), placeCaption: "Nine Mile, Jamaica — his birthplace and mausoleum",
    portrait: WM("wikipedia/commons/2/2d/Bob_Marley_1976_press_photo.jpg"),
    quote: "One good thing about music, when it hits you, you feel no pain.",
    legacy: "Carried reggae and a message of unity from Jamaica to the world." },
  { name: "Ella Fitzgerald", years: "1917–1996", emoji: "🎤", scene: "concert", place: WM("wikipedia/commons/thumb/d/de/Harlem_-_Apollo_Theater_%2848555309512%29.jpg/1280px-Harlem_-_Apollo_Theater_%2848555309512%29.jpg"), placeCaption: "the Apollo Theater, Harlem — where she got her start",
    portrait: WM("wikipedia/commons/thumb/a/a4/Ella_Fitzgerald_6_%28cropped%29.jpg/960px-Ella_Fitzgerald_6_%28cropped%29.jpg"),
    quote: "The only thing better than singing is more singing.",
    legacy: "The 'First Lady of Song,' famed for her flawless scat singing and phrasing." },
  { name: "Freddie Mercury", years: "1946–1991", emoji: "🎤", scene: "concert", place: WM("wikipedia/commons/thumb/7/73/Zanzibar_sultan_palace.jpg/1280px-Zanzibar_sultan_palace.jpg"), placeCaption: "Stone Town, Zanzibar — his birthplace",
    portrait: WM("wikipedia/commons/thumb/e/ef/Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg/960px-Freddie_Mercury_performing_in_New_Haven%2C_CT%2C_November_1977.jpg"),
    quote: "I won't be a rock star. I will be a legend.",
    legacy: "Queen's frontman whose four-octave range redefined rock showmanship." },
  { name: "Miles Davis", years: "1926–1991", emoji: "🎺", scene: "concert", place: WM("wikipedia/commons/thumb/9/9e/Altonbridge.jpg/1280px-Altonbridge.jpg"), placeCaption: "Alton, Illinois — his birthplace",
    portrait: WM("wikipedia/commons/thumb/b/b7/Miles_Davis_1987.png/960px-Miles_Davis_1987.png"),
    quote: "Do not fear mistakes. There are none.",
    legacy: "Reinvented jazz repeatedly, from bebop to modal to fusion." },
  { name: "Duke Ellington", years: "1899–1974", emoji: "🎹", scene: "concert", place: WM("wikipedia/commons/a/af/Duke_Ellington_-_publicity.JPG"), placeCaption: "the Cotton Club, Harlem — his orchestra’s longtime home",
    portrait: WM("wikipedia/commons/thumb/a/af/Duke_Ellington_-_publicity.JPG/960px-Duke_Ellington_-_publicity.JPG"),
    quote: "A problem is a chance for you to do your best.",
    legacy: "Led his orchestra for nearly 50 years, composing some 3,000 works and elevating jazz to art music." },
  { name: "Jimi Hendrix", years: "1942–1970", emoji: "🎸", scene: "concert", place: WM("wikipedia/commons/thumb/5/58/Seattle_Center_as_night_falls.jpg/1280px-Seattle_Center_as_night_falls.jpg"), placeCaption: "Seattle — his hometown",
    portrait: WM("wikipedia/commons/thumb/a/aa/Jimi_Hendrix_%281967%29_%28cropped%29.jpg/960px-Jimi_Hendrix_%281967%29_%28cropped%29.jpg"),
    quote: "Knowledge speaks, but wisdom listens.",
    legacy: "Redefined the electric guitar's possibilities in a career spanning barely four years." },
  { name: "Maria Callas", years: "1923–1977", emoji: "🎭", scene: "concert", place: WM("wikipedia/commons/thumb/7/71/Exterior_Teatro_Alla_Scala_high_quality_01.jpg/1280px-Exterior_Teatro_Alla_Scala_high_quality_01.jpg"), placeCaption: "La Scala, Milan — the opera house of her greatest triumphs",
    portrait: WM("wikipedia/commons/thumb/a/a1/Maria_Callas_1958.jpg/960px-Maria_Callas_1958.jpg"),
    quote: "Art is domination — it's making people accept your point of view.",
    legacy: "Her dramatic intensity redefined operatic performance in the 20th century." },
  { name: "Ravi Shankar", years: "1920–2012", emoji: "🎻", scene: "concert", place: WM("wikipedia/commons/thumb/0/0e/Varanasi%2C_India%2C_Ghats%2C_Cremation_ceremony_in_progress.jpg/1280px-Varanasi%2C_India%2C_Ghats%2C_Cremation_ceremony_in_progress.jpg"), placeCaption: "Varanasi — his birthplace on the Ganges",
    portrait: WM("wikipedia/commons/thumb/6/60/Ravi_Shankar.jpg/960px-Ravi_Shankar.jpg"),
    quote: "To me, music is a divine art form.",
    legacy: "Brought the sitar and Indian classical music to global audiences." },

  // ── Sports ───────────────────────────────────────────────────────────
  { name: "Muhammad Ali", years: "1942–2016", emoji: "🥊", scene: "stadium", place: WM("wikipedia/commons/thumb/5/55/Louisville_Skyline_2021_%283%29.jpg/1280px-Louisville_Skyline_2021_%283%29.jpg"), placeCaption: "Louisville, Kentucky — his hometown",
    portrait: WM("wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/960px-Muhammad_Ali_NYWTS.jpg"),
    quote: "Float like a butterfly, sting like a bee.",
    legacy: "Three-time heavyweight champion who became a global icon beyond boxing." },
  { name: "Jesse Owens", years: "1913–1980", emoji: "🏃", scene: "stadium", place: WM("wikipedia/commons/thumb/5/5c/Olympiastadion_Berlin-Marathontor-msu-2020-3139.jpg/1280px-Olympiastadion_Berlin-Marathontor-msu-2020-3139.jpg"), placeCaption: "Olympiastadion Berlin — site of his 1936 triumph",
    portrait: WM("wikipedia/commons/1/19/Jesse_Owens_1936.jpg"),
    quote: "We all have dreams. But in order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline, and effort.",
    legacy: "Won four gold medals at the 1936 Berlin Olympics, defying Nazi ideology." },
  { name: "Pelé", years: "1940–2022", emoji: "⚽", scene: "stadium", place: WM("wikipedia/commons/thumb/a/a4/Maracana_2022.jpg/1280px-Maracana_2022.jpg"), placeCaption: "Maracanã Stadium, Rio de Janeiro",
    portrait: WM("wikipedia/commons/5/5e/Pele_con_brasil_%28cropped%29.jpg"),
    quote: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.",
    legacy: "Won three World Cups and became football's first true global superstar." },
  { name: "Serena Williams", years: "1981–", emoji: "🎾", scene: "stadium", place: WM("wikipedia/commons/5/5b/Compton_martin_luther_king_monument.jpg"), placeCaption: "Compton, California — where she trained growing up",
    portrait: WM("wikipedia/commons/2/2f/Guests_at_the_2026_Met_Gala_209_%28cropped%29.jpg"),
    quote: "I really think a champion is defined not by their wins but by how they can recover when they fall.",
    legacy: "Won 23 Grand Slam singles titles, the most of any player in the Open Era." },
  { name: "Michael Jordan", years: "1963–", emoji: "🏀", scene: "stadium", place: WM("wikipedia/commons/thumb/2/22/United_Center_1.jpg/1280px-United_Center_1.jpg"), placeCaption: "the United Center, Chicago — home of the Bulls",
    portrait: WM("wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg"),
    quote: "I've missed more than 9,000 shots in my career… I have failed over and over and over again in my life. And that is why I succeed.",
    legacy: "Six NBA championships and arguably basketball's greatest player." },
  { name: "Billie Jean King", years: "1943–", emoji: "🎾", scene: "stadium", place: WM("wikipedia/commons/c/c8/Long_beach3_%28cropped%29.jpg"), placeCaption: "Long Beach, California — her birthplace",
    portrait: WM("wikipedia/commons/thumb/b/bd/Billie_Jean_King_at_the_2026_Sundance_Film_Festival_02_%28crop_2%29.jpg/960px-Billie_Jean_King_at_the_2026_Sundance_Film_Festival_02_%28crop_2%29.jpg"),
    quote: "Pressure is a privilege.",
    legacy: "Won the 'Battle of the Sexes' and fought for equal pay in tennis." },
  { name: "Wilma Rudolph", years: "1940–1994", emoji: "🏃", scene: "stadium", place: WM("wikipedia/commons/thumb/5/58/Downtown_Clarksville_TN.jpg/1280px-Downtown_Clarksville_TN.jpg"), placeCaption: "Clarksville, Tennessee — her hometown",
    portrait: WM("wikipedia/commons/thumb/5/52/Wilma_Rudolph_1960.jpg/960px-Wilma_Rudolph_1960.jpg"),
    quote: "Never underestimate the power of dreams and the influence of the human spirit.",
    legacy: "Overcame childhood polio to become the first American woman to win three gold medals in a single Olympics." },
  { name: "Roger Bannister", years: "1929–2018", emoji: "🏃", scene: "stadium", place: WM("wikipedia/commons/a/ae/The_Grandstand_at_the_Sir_Roger_Bannister_running_track.jpg"), placeCaption: "Iffley Road Stadium, Oxford — where he broke the four-minute mile",
    portrait: WM("wikipedia/commons/thumb/c/c3/Roger_Bannister_2.jpg/960px-Roger_Bannister_2.jpg"),
    quote: "The man who can drive himself further once the effort gets painful is the man who will win.",
    legacy: "The first person to run a mile in under four minutes, in 1954." },
  { name: "Babe Ruth", years: "1895–1948", emoji: "⚾", scene: "stadium", place: WM("wikipedia/commons/thumb/a/af/Yankee_Stadium_overhead_2010.jpg/1280px-Yankee_Stadium_overhead_2010.jpg"), placeCaption: "Yankee Stadium — \"The House That Ruth Built\"",
    portrait: WM("wikipedia/commons/thumb/1/13/Babe_Ruth2.jpg/960px-Babe_Ruth2.jpg"),
    quote: "Every strike brings me closer to the next home run.",
    legacy: "Redefined baseball with his power hitting for the New York Yankees." },
  { name: "Simone Biles", years: "1997–", emoji: "🤸", scene: "stadium", place: WM("wikipedia/commons/3/32/Spring_Texas_WS_%281_of_1%29.jpg"), placeCaption: "Spring, Texas — her hometown",
    portrait: WM("wikipedia/commons/thumb/f/f6/Simone_Biles_National_Team_2024.jpg/960px-Simone_Biles_National_Team_2024.jpg"),
    quote: "I'd rather regret the risks that didn't work out than the chances I didn't take.",
    legacy: "The most decorated gymnast in World Championship history." },
  { name: "Usain Bolt", years: "1986–", emoji: "🏃", scene: "stadium", place: WM("wikipedia/commons/9/99/PortofKingston.jpg"), placeCaption: "Kingston, Jamaica",
    portrait: WM("wikipedia/commons/c/c3/Usain_Bolt_smiling_Berlin_2009.JPG"),
    quote: "Fear is not an option.",
    legacy: "The fastest man ever timed, with eight Olympic gold medals." },
  { name: "Jackie Robinson", years: "1919–1972", emoji: "⚾", scene: "stadium", place: WM("wikipedia/commons/thumb/7/78/Ebbets1913OpeningDay.jpg/1280px-Ebbets1913OpeningDay.jpg"), placeCaption: "Ebbets Field, Brooklyn — where he broke the color barrier",
    portrait: WM("wikipedia/commons/thumb/b/bd/Jackie_Robinson%2C_NPG_97_135.jpg/960px-Jackie_Robinson%2C_NPG_97_135.jpg"),
    quote: "A life is not important except in the impact it has on other lives.",
    legacy: "Broke Major League Baseball's color barrier in 1947." },
  { name: "Wayne Gretzky", years: "1961–", emoji: "🏒", scene: "stadium", place: WM("wikipedia/commons/b/b7/Brantford_Montage.jpg"), placeCaption: "Brantford, Ontario — his hometown",
    portrait: WM("wikipedia/commons/thumb/c/cc/Andrew_Scheer_with_Wayne_Gretzky_%2848055697168%29_%28cropped%29.jpg/960px-Andrew_Scheer_with_Wayne_Gretzky_%2848055697168%29_%28cropped%29.jpg"),
    quote: "You miss 100% of the shots you don't take.",
    legacy: "Hockey's all-time leading scorer, known simply as 'The Great One.'" },
  { name: "Kareem Abdul-Jabbar", years: "1947–", emoji: "🏀", scene: "stadium", place: WM("wikipedia/commons/thumb/a/a6/Harlem_04.jpg/1280px-Harlem_04.jpg"), placeCaption: "Harlem, New York — his birthplace",
    portrait: WM("wikipedia/commons/thumb/a/a0/Kareem_Abdul-Jabbar_May_2014.jpg/960px-Kareem_Abdul-Jabbar_May_2014.jpg"),
    quote: "You can't win unless you learn how to lose.",
    legacy: "The NBA's career scoring leader for nearly four decades." },

  // ── Business & invention ─────────────────────────────────────────────
  { name: "Ada Lovelace", years: "1815–1852", emoji: "⚙️", scene: "engine", place: WM("wikipedia/commons/thumb/6/67/London_Skyline_%28125508655%29.jpeg/1280px-London_Skyline_%28125508655%29.jpeg"), placeCaption: "London — where she worked with Charles Babbage",
    portrait: WP("Ada_Lovelace_portrait.jpg"),
    quote: "That brain of mine is something more than merely mortal, as time will show.",
    legacy: "Wrote what is regarded as the first algorithm intended for a machine." },
  { name: "Thomas Edison", years: "1847–1931", emoji: "💡", scene: "factory", place: WM("wikipedia/commons/thumb/4/45/Thomas_Edison_Tower.jpg/1280px-Thomas_Edison_Tower.jpg"), placeCaption: "Menlo Park, New Jersey — his \"invention factory\"",
    portrait: WM("wikipedia/commons/thumb/9/9d/Thomas_Edison2.jpg/960px-Thomas_Edison2.jpg"),
    quote: "I have not failed. I've just found 10,000 ways that won't work.",
    legacy: "Held 1,093 US patents, including the practical incandescent light bulb." },
  { name: "Henry Ford", years: "1863–1947", emoji: "🚗", scene: "factory", place: WM("wikipedia/commons/thumb/5/56/Former_city_hall_during_Memorial_Day_Parade%2C_Dearborn%2C_Michigan.jpg/1280px-Former_city_hall_during_Memorial_Day_Parade%2C_Dearborn%2C_Michigan.jpg"), placeCaption: "Dearborn, Michigan — home of Ford’s headquarters",
    portrait: WM("wikipedia/commons/thumb/2/27/Henry_Ford_portrait_1915_original_%283x4_cropped%29.png/960px-Henry_Ford_portrait_1915_original_%283x4_cropped%29.png"),
    quote: "Whether you think you can, or you think you can't – you're right.",
    legacy: "The moving assembly line made the automobile affordable for millions." },
  { name: "Steve Jobs", years: "1955–2011", emoji: "📱", scene: "engine", place: WM("wikipedia/commons/4/43/Cupertino_City_Center.jpg"), placeCaption: "Cupertino, California — Apple’s home",
    portrait: WM("wikipedia/commons/thumb/5/51/Steve_Jobs_Headshot_2010_%28cropped_4%29.jpg/960px-Steve_Jobs_Headshot_2010_%28cropped_4%29.jpg"),
    quote: "Your time is limited, so don't waste it living someone else's life.",
    legacy: "Co-founded Apple and redefined personal computing, music, and phones." },
  { name: "Benjamin Franklin", years: "1706–1790", emoji: "🔑", scene: "lab", place: WM("wikipedia/commons/thumb/1/19/Philadelphia_skyline_20240528_%28cropped_2-1%29.jpg/1280px-Philadelphia_skyline_20240528_%28cropped_2-1%29.jpg"), placeCaption: "Philadelphia — his adopted hometown",
    portrait: WM("wikipedia/commons/thumb/8/87/Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg/960px-Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg"),
    quote: "An investment in knowledge pays the best interest.",
    legacy: "Statesman, scientist, and inventor of the lightning rod and bifocals." },
  { name: "Grace Hopper", years: "1906–1992", emoji: "💻", scene: "engine", place: WM("wikipedia/commons/thumb/c/cc/Harvard_University_coat_of_arms.svg/1280px-Harvard_University_coat_of_arms.svg.png"), placeCaption: "Harvard University — home of the Mark I computer she programmed",
    portrait: WM("wikipedia/commons/thumb/9/98/Commodore_Grace_M._Hopper%2C_USN_%28covered%29_head_and_shoulders_crop.jpg/960px-Commodore_Grace_M._Hopper%2C_USN_%28covered%29_head_and_shoulders_crop.jpg"),
    quote: "The most dangerous phrase in the language is, 'We've always done it this way.'",
    legacy: "Pioneered computer programming and invented the first compiler." },
  { name: "Madam C. J. Walker", years: "1867–1919", emoji: "💼", scene: "factory", place: WM("wikipedia/commons/thumb/c/c6/Indianapolis-1872529_1920_%28cropped%29.jpg/1280px-Indianapolis-1872529_1920_%28cropped%29.jpg"), placeCaption: "Indianapolis — headquarters of her hair-care empire",
    portrait: WM("wikipedia/commons/thumb/d/dc/Madam_C._J._Walker_by_Addison_N._Scurlock.jpg/960px-Madam_C._J._Walker_by_Addison_N._Scurlock.jpg"),
    quote: "I got my start by giving myself a start.",
    legacy: "Built a haircare empire and became America's first self-made female millionaire." },
  { name: "Walt Disney", years: "1901–1966", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/b/bd/Sleeping_Beauty_Castle_-_February_2024.png/1280px-Sleeping_Beauty_Castle_-_February_2024.png"), placeCaption: "Disneyland, Anaheim — his flagship creation",
    portrait: WM("wikipedia/commons/5/50/Walt_Disney_1946_%28cropped2%29.JPG"),
    quote: "All our dreams can come true, if we have the courage to pursue them.",
    legacy: "Built an animation studio into a global entertainment empire." },
  { name: "Warren Buffett", years: "1930–", emoji: "💰", scene: "engine", place: WM("wikipedia/commons/thumb/b/b6/City_of_Omaha%2C_Nebraska_Skyline_on_the_Missouri_River_%2830899969517%29.jpg/1280px-City_of_Omaha%2C_Nebraska_Skyline_on_the_Missouri_River_%2830899969517%29.jpg"), placeCaption: "Omaha, Nebraska — Berkshire Hathaway’s home",
    portrait: WM("wikipedia/commons/d/d4/Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg"),
    quote: "Someone's sitting in the shade today because someone planted a tree a long time ago.",
    legacy: "Built Berkshire Hathaway into one of history's most successful investment firms." },
  { name: "Katharine Graham", years: "1917–2001", emoji: "📰", scene: "library", place: WM("wikipedia/commons/thumb/e/e4/12-07-13-washington-by-RalfR-08.jpg/1280px-12-07-13-washington-by-RalfR-08.jpg"), placeCaption: "Washington, D.C. — where she led The Washington Post",
    portrait: WM("wikipedia/commons/thumb/6/65/Katharine_Graham_927-9432_%28cropped_retouched%29.jpg/960px-Katharine_Graham_927-9432_%28cropped_retouched%29.jpg"),
    quote: "To love what you do and feel that it matters, how could anything be more fun?",
    legacy: "Led The Washington Post through Watergate as one of the era's few female publishers." },
  { name: "Johannes Gutenberg", years: "c.1400–1468", emoji: "🖨️", scene: "factory", place: WM("wikipedia/commons/thumb/c/c6/Mainzer_Dom_Blaue_Stunde_%2837539430014%29.jpg/1280px-Mainzer_Dom_Blaue_Stunde_%2837539430014%29.jpg"), placeCaption: "Mainz, Germany — his birthplace",
    portrait: WM("wikipedia/commons/5/5b/Mainz_Gutenbergdenkmal_2016_%28cropped%29.jpg"),
    quote: "It is a press, certainly, but a press from which shall flow in inexhaustible streams the most abundant liquor that has ever flowed to relieve the thirst of men.",
    legacy: "His printing press with movable type made mass literacy possible." },
  { name: "Sam Walton", years: "1918–1992", emoji: "🏪", scene: "factory", place: WM("wikipedia/commons/thumb/b/b4/Central_Avenue_at_night.jpg/1280px-Central_Avenue_at_night.jpg"), placeCaption: "Bentonville, Arkansas — Walmart’s birthplace",
    portrait: WM("wikipedia/commons/d/d0/Sam-Walton.jpg"),
    quote: "High expectations are the key to everything.",
    legacy: "Built Walmart from a single Arkansas store into the world's largest retailer." },
  { name: "Estée Lauder", years: "1906–2004", emoji: "💄", scene: "factory", place: WM("wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/1280px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg"), placeCaption: "New York City — where she built her cosmetics empire",
    portrait: WM("wikipedia/commons/thumb/7/7e/Estee_Lauder_NYWTS.jpg/960px-Estee_Lauder_NYWTS.jpg"),
    quote: "I have never worked a day in my life without selling. If I believe in something, I sell it, and I sell it hard.",
    legacy: "Built a global cosmetics empire from a handful of homemade creams." },
  { name: "Ray Kroc", years: "1902–1984", emoji: "🍔", scene: "factory", place: WM("wikipedia/commons/thumb/7/7e/Des_Plaines%2C_IL.jpg/1280px-Des_Plaines%2C_IL.jpg"), placeCaption: "Des Plaines, Illinois — site of the first Kroc-run McDonald’s",
    portrait: WM("wikipedia/commons/a/a0/Ray_Kroc_1978.jpg"),
    quote: "Press on: nothing in the world can take the place of persistence.",
    legacy: "Franchised McDonald's into the world's largest restaurant chain." },
  { name: "Mary Kay Ash", years: "1918–2001", emoji: "💄", scene: "factory", place: WM("wikipedia/commons/thumb/0/03/View_of_Dallas_from_Reunion_Tower_August_2015_05.jpg/1280px-View_of_Dallas_from_Reunion_Tower_August_2015_05.jpg"), placeCaption: "Dallas, Texas — Mary Kay’s headquarters", portrait: "",
    quote: "Ideas are a dime a dozen. People who implement them are priceless.",
    legacy: "Built Mary Kay Cosmetics into a direct-sales empire that champions female entrepreneurs." },
  { name: "George Westinghouse", years: "1846–1914", emoji: "🔌", scene: "factory", place: WM("wikipedia/commons/thumb/d/d6/Ascending_the_Duquesne_Incline.jpg/1280px-Ascending_the_Duquesne_Incline.jpg"), placeCaption: "Pittsburgh — home of Westinghouse Electric",
    portrait: WM("wikipedia/commons/thumb/5/5b/George_Westinghouse_1884.png/960px-George_Westinghouse_1884.png"),
    quote: "If someday they say of me that in my work I have contributed something to the welfare and happiness of my fellow man, I shall be satisfied.",
    legacy: "Championed AC power and held nearly 400 patents in his lifetime." },

  // ── Activism & politics ──────────────────────────────────────────────
  { name: "Frederick Douglass", years: "1818–1895", emoji: "📢", scene: "lectern", place: WM("wikipedia/commons/thumb/6/65/Oxford-Bellevue_Ferry_MD1.jpg/1280px-Oxford-Bellevue_Ferry_MD1.jpg"), placeCaption: "Talbot County, Maryland — his birthplace into slavery",
    portrait: WP("Frederick_Douglass_(circa_1879).jpg"),
    quote: "If there is no struggle, there is no progress.",
    legacy: "Escaped slavery to become one of history's most powerful voices for human freedom." },
  { name: "Martin Luther King Jr.", years: "1929–1968", emoji: "✊", scene: "rally", place: WM("wikipedia/commons/thumb/c/c8/A2ATL20250614-0721_%28cropped%29.jpg/1280px-A2ATL20250614-0721_%28cropped%29.jpg"), placeCaption: "Atlanta — his birthplace and home church",
    portrait: WM("wikipedia/commons/thumb/0/05/Martin_Luther_King%2C_Jr..jpg/960px-Martin_Luther_King%2C_Jr..jpg"),
    quote: "Darkness cannot drive out darkness; only light can do that.",
    legacy: "Led the American civil rights movement through nonviolent resistance." },
  { name: "Nelson Mandela", years: "1918–2013", emoji: "🗽", scene: "rally", place: WM("wikipedia/commons/thumb/2/24/Robben_Island_-_Cape_Town%2C_South_Africa_%283883849594%29.jpg/1280px-Robben_Island_-_Cape_Town%2C_South_Africa_%283883849594%29.jpg"), placeCaption: "Robben Island — where he was imprisoned for 18 years",
    portrait: WM("wikipedia/commons/thumb/0/02/Nelson_Mandela_1994.jpg/960px-Nelson_Mandela_1994.jpg"),
    quote: "It always seems impossible until it's done.",
    legacy: "Spent 27 years imprisoned before leading South Africa's transition from apartheid." },
  { name: "Mahatma Gandhi", years: "1869–1948", emoji: "🕊️", scene: "rally", place: WM("wikipedia/commons/thumb/7/74/The_main_memorial_near_the_house.jpg/1280px-The_main_memorial_near_the_house.jpg"), placeCaption: "Porbandar, India — his birthplace",
    portrait: WM("wikipedia/commons/thumb/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg/960px-Mahatma-Gandhi%2C_studio%2C_1931.jpg"),
    quote: "An eye for an eye only ends up making the whole world blind.",
    legacy: "Led India to independence through a philosophy of nonviolent civil disobedience." },
  { name: "Susan B. Anthony", years: "1820–1906", emoji: "🗳️", scene: "rally", place: WM("wikipedia/commons/e/e9/Downtown_Rochester%2C_NY_HDR_by_patrickashley.jpg"), placeCaption: "Rochester, New York — her home for 40 years",
    portrait: WM("wikipedia/commons/thumb/2/28/SB_Anthony_from_RoRaWW.jpg/960px-SB_Anthony_from_RoRaWW.jpg"),
    quote: "Failure is impossible.",
    legacy: "Campaigned for decades for women's suffrage in the United States." },
  { name: "Eleanor Roosevelt", years: "1884–1962", emoji: "🕊️", scene: "lectern", place: WM("wikipedia/commons/thumb/1/12/Stone_Cottage_Val-Kill_NY1.jpg/1280px-Stone_Cottage_Val-Kill_NY1.jpg"), placeCaption: "Val-Kill, Hyde Park — her country retreat",
    portrait: WM("wikipedia/commons/thumb/7/7d/Eleanor_Roosevelt_at_the_United_Nations%2C_circa_1946-1947_%283x4_cropped%29.jpg/960px-Eleanor_Roosevelt_at_the_United_Nations%2C_circa_1946-1947_%283x4_cropped%29.jpg"),
    quote: "No one can make you feel inferior without your consent.",
    legacy: "Reshaped the First Lady's role and helped draft the Universal Declaration of Human Rights." },
  { name: "Malala Yousafzai", years: "2003–", emoji: "📚", scene: "lectern", place: WM("wikipedia/commons/thumb/9/96/Mahodand_l.jpg/1280px-Mahodand_l.jpg"), placeCaption: "the Swat Valley, Pakistan — her home region",
    portrait: WM("wikipedia/commons/thumb/0/03/Malala_Yousafzai_2023_portrait_2x3.jpg/960px-Malala_Yousafzai_2023_portrait_2x3.jpg"),
    quote: "One child, one teacher, one book, one pen can change the world.",
    legacy: "The youngest-ever Nobel laureate, campaigning for girls' education after surviving an assassination attempt." },
  { name: "Abraham Lincoln", years: "1809–1865", emoji: "🏛️", scene: "forum", place: WM("wikipedia/commons/thumb/8/88/Dana-Thomas_House%2C_Lawrence_Avenue_and_4th_Street%2C_Springfield%2C_IL_-_53322374502.jpg/1280px-Dana-Thomas_House%2C_Lawrence_Avenue_and_4th_Street%2C_Springfield%2C_IL_-_53322374502.jpg"), placeCaption: "Springfield, Illinois — his home before the presidency",
    portrait: WM("wikipedia/commons/thumb/5/57/Abraham_Lincoln_1863_Portrait_%283x4_cropped%29.jpg/960px-Abraham_Lincoln_1863_Portrait_%283x4_cropped%29.jpg"),
    quote: "Whatever you are, be a good one.",
    legacy: "Led the United States through the Civil War and abolished slavery." },
  { name: "Winston Churchill", years: "1874–1965", emoji: "🎖️", scene: "forum", place: WM("wikipedia/commons/thumb/7/71/Blenheim_Palace_North_Gate_2014.jpg/1280px-Blenheim_Palace_North_Gate_2014.jpg"), placeCaption: "Blenheim Palace — his birthplace",
    portrait: WM("wikipedia/commons/thumb/0/02/Sir_Winston_Churchill_-_19086236948_%28restored%29.jpg/960px-Sir_Winston_Churchill_-_19086236948_%28restored%29.jpg"),
    quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    legacy: "Led Britain through the Second World War with defiant wartime oratory." },
  { name: "Rosa Parks", years: "1913–2005", emoji: "🚌", scene: "rally", place: WM("wikipedia/commons/thumb/6/61/Aerial_view_of_Montgomery%2C_Alabama_LCCN2011646683.jpg/1280px-Aerial_view_of_Montgomery%2C_Alabama_LCCN2011646683.jpg"), placeCaption: "Montgomery, Alabama — site of the bus boycott",
    portrait: WM("wikipedia/commons/thumb/b/b1/Rosa_Parks%2C_November_1956_%28cropped%29.jpg/960px-Rosa_Parks%2C_November_1956_%28cropped%29.jpg"),
    quote: "You must never be fearful about what you are doing when it is right.",
    legacy: "Her refusal to give up her bus seat helped ignite the Montgomery bus boycott." },
  { name: "Cesar Chavez", years: "1927–1993", emoji: "✊", scene: "rally", place: WM("wikipedia/commons/3/33/City_of_Delano_entry_signage_%28cropped%29.jpg"), placeCaption: "Delano, California — site of the historic grape strike",
    portrait: WM("wikipedia/commons/thumb/2/26/Cesar_Chavez_40915a_%28cropped2%29.tif/lossy-page1-960px-Cesar_Chavez_40915a_%28cropped2%29.tif.jpg"),
    quote: "We cannot seek achievement for ourselves and forget about progress and prosperity for our community.",
    legacy: "Co-founded the United Farm Workers and championed nonviolent labor organizing." },
  { name: "Aung San Suu Kyi", years: "1945–", emoji: "🕊️", scene: "lectern", place: WM("wikipedia/commons/b/b9/ShwedagonPagoda.jpg"), placeCaption: "Yangon, Myanmar — where she spent 15 years under house arrest",
    portrait: WM("wikipedia/commons/9/97/Aung_San_Suu_Kyi_at_the_Enthronement_of_Naruhito_%281%29.jpg"),
    quote: "It is not power that corrupts but fear.",
    legacy: "Led Myanmar's democracy movement and endured 15 years under house arrest." },
  { name: "Harriet Tubman", years: "1822–1913", emoji: "🌟", scene: "rally", place: WM("wikipedia/commons/thumb/a/a5/Dorchester_County_Courthouse.jpg/1280px-Dorchester_County_Courthouse.jpg"), placeCaption: "Dorchester County, Maryland — her birthplace into slavery",
    portrait: WM("wikipedia/commons/thumb/b/b4/Carte-de-visite_portrait_of_Harriet_Tubman_%28cropped%29.jpg/960px-Carte-de-visite_portrait_of_Harriet_Tubman_%28cropped%29.jpg"),
    quote: "I was the conductor of the Underground Railroad for eight years, and I can say what most conductors can't say — I never ran my train off the track and I never lost a passenger.",
    legacy: "Escaped slavery and led dozens of others to freedom via the Underground Railroad." },
  { name: "Desmond Tutu", years: "1931–2021", emoji: "⛪", scene: "temple", place: WM("wikipedia/commons/thumb/8/8d/Camps_bay_%2853460319478%29_%28cropped%29.jpg/1280px-Camps_bay_%2853460319478%29_%28cropped%29.jpg"), placeCaption: "Cape Town — where he served as archbishop",
    portrait: WM("wikipedia/commons/thumb/e/e4/Archbishop-Tutu-medium.jpg/960px-Archbishop-Tutu-medium.jpg"),
    quote: "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.",
    legacy: "Led the fight against apartheid and chaired South Africa's Truth and Reconciliation Commission." },
  { name: "Emmeline Pankhurst", years: "1858–1928", emoji: "🗳️", scene: "rally", place: WM("wikipedia/commons/8/8c/Tower_Blocks_over_Knott_Mill%2C_geograph_6866152_by_David_Dixon.jpg"), placeCaption: "Manchester — her birthplace, where she founded the WSPU",
    portrait: WM("wikipedia/commons/thumb/2/25/Emmeline_Pankhurst%2C_seated_%281913%29.jpg/960px-Emmeline_Pankhurst%2C_seated_%281913%29.jpg"),
    quote: "We are here, not because we are law-breakers; we are here in our efforts to become law-makers.",
    legacy: "Led the militant campaign that won British women the right to vote." },
  { name: "Ruth Bader Ginsburg", years: "1933–2020", emoji: "⚖️", scene: "forum", place: WM("wikipedia/commons/thumb/f/f3/Seal_of_the_United_States_Supreme_Court.svg/1280px-Seal_of_the_United_States_Supreme_Court.svg.png"), placeCaption: "the U.S. Supreme Court, where she served 27 years",
    portrait: WM("wikipedia/commons/thumb/7/76/Ruth_Bader_Ginsburg_2016_portrait.jpg/960px-Ruth_Bader_Ginsburg_2016_portrait.jpg"),
    quote: "Fight for the things that you care about, but do it in a way that will lead others to join you.",
    legacy: "Fought for gender equality and served 27 years on the US Supreme Court." },

  // ── Exploration ──────────────────────────────────────────────────────
  { name: "Ernest Shackleton", years: "1874–1922", emoji: "⛵", scene: "ocean", place: WM("wikipedia/commons/thumb/3/32/South_Georgia_Island_as_seen_by_Sentinel-2.jpg/1280px-South_Georgia_Island_as_seen_by_Sentinel-2.jpg"), placeCaption: "South Georgia Island — where the Endurance expedition ended",
    portrait: WM("wikipedia/commons/thumb/b/bd/Ernest_Shackleton_before_1909.jpg/960px-Ernest_Shackleton_before_1909.jpg"),
    quote: "Difficulties are just things to overcome, after all.",
    legacy: "Led his crew to safety after their ship was crushed by Antarctic ice." },
  { name: "Amelia Earhart", years: "1897–1937", emoji: "✈️", scene: "mountain", place: WM("wikipedia/commons/thumb/4/45/Atchison_County_Kansas_Incorporated_and_Unincorporated_areas_Atchison_Highlighted.svg/1280px-Atchison_County_Kansas_Incorporated_and_Unincorporated_areas_Atchison_Highlighted.svg.png"), placeCaption: "Atchison, Kansas — her birthplace",
    portrait: WM("wikipedia/commons/7/72/Amelia_Earhart_standing_under_nose_of_her_Lockheed_Model_10-E_Electra%2C_small_%28cropped%29.jpg"),
    quote: "The most effective way to do it, is to do it.",
    legacy: "The first woman to fly solo across the Atlantic Ocean." },
  { name: "Neil Armstrong", years: "1930–2012", emoji: "🚀", scene: "cosmos", place: WM("wikipedia/commons/thumb/5/5e/Wapakoneta-ohio-downtown.jpg/1280px-Wapakoneta-ohio-downtown.jpg"), placeCaption: "Wapakoneta, Ohio — his birthplace",
    portrait: WM("wikipedia/commons/thumb/0/0d/Neil_Armstrong_pose.jpg/960px-Neil_Armstrong_pose.jpg"),
    quote: "That's one small step for man, one giant leap for mankind.",
    legacy: "The first human to walk on the Moon, in July 1969." },
  { name: "Marco Polo", years: "1254–1324", emoji: "🐫", scene: "mountain", place: WM("wikipedia/commons/thumb/4/4f/Venezia_aerial_view.jpg/1280px-Venezia_aerial_view.jpg"), placeCaption: "Venice — his home city",
    portrait: WM("wikipedia/commons/f/ff/Frontispice_%C3%A9dition_de_Nuremberg_1477_%28cropped%29.png"),
    quote: "I did not tell half of what I saw.",
    legacy: "His travels across Asia introduced Europe to the wonders of the East." },
  { name: "Yuri Gagarin", years: "1934–1968", emoji: "🚀", scene: "cosmos", place: WM("wikipedia/commons/thumb/5/51/Baikonur_Cosmodrome_Soyuz_launch_pad.jpg/1280px-Baikonur_Cosmodrome_Soyuz_launch_pad.jpg"), placeCaption: "Baikonur Cosmodrome — his launch site",
    portrait: WM("wikipedia/commons/thumb/d/d8/Yuri_Gagarin_with_awards_%28cropped%29_2.jpg/960px-Yuri_Gagarin_with_awards_%28cropped%29_2.jpg"),
    quote: "I see Earth! It is so beautiful.",
    legacy: "The first human to journey into outer space, in 1961." },
  { name: "Edmund Hillary", years: "1919–2008", emoji: "🏔️", scene: "mountain", place: WM("wikipedia/commons/thumb/1/15/Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg/1280px-Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg"), placeCaption: "Mount Everest — the summit he was first to reach",
    portrait: WM("wikipedia/commons/thumb/7/76/Edmund_Hillary%2C_c._1953%2C_autograph_removed.jpg/960px-Edmund_Hillary%2C_c._1953%2C_autograph_removed.jpg"),
    quote: "It is not the mountain we conquer, but ourselves.",
    legacy: "First confirmed, with Tenzing Norgay, to summit Mount Everest, in 1953." },
  { name: "Sally Ride", years: "1951–2012", emoji: "🚀", scene: "cosmos", place: WM("wikipedia/commons/thumb/4/46/NASA_logo_%282023_colors%29.svg/1280px-NASA_logo_%282023_colors%29.svg.png"), placeCaption: "Kennedy Space Center — her launch site",
    portrait: WM("wikipedia/commons/thumb/0/0c/Sally_Ride_%281984%29.jpg/960px-Sally_Ride_%281984%29.jpg"),
    quote: "I would like to be remembered as someone who was not afraid to do what she wanted to do.",
    legacy: "The first American woman in space, aboard the Challenger in 1983." },
  { name: "Roald Amundsen", years: "1872–1928", emoji: "🧭", scene: "mountain", place: WM("wikipedia/commons/5/59/Pole-south.gif"), placeCaption: "the South Pole — the first place he reached",
    portrait: WM("wikipedia/commons/thumb/6/6f/Amundsen_in_fur_skins.jpg/960px-Amundsen_in_fur_skins.jpg"),
    quote: "Adventure is just bad planning.",
    legacy: "Led the first expedition to reach the South Pole, in 1911." },
  { name: "Robert Falcon Scott", years: "1868–1912", emoji: "❄️", scene: "mountain", place: WM("wikipedia/commons/5/59/Pole-south.gif"), placeCaption: "the South Pole — the goal of his fatal expedition",
    portrait: WM("wikipedia/commons/thumb/7/72/Scott_of_the_Antarctic_%28bw%29_%28cropped%29.jpg/960px-Scott_of_the_Antarctic_%28bw%29_%28cropped%29.jpg"),
    quote: "We are showing that Englishmen can still die with a bold spirit, fighting it out to the end.",
    legacy: "Led the ill-fated Terra Nova expedition to the South Pole in 1912, dying on the return journey." },
  { name: "Mae Jemison", years: "1956–", emoji: "🚀", scene: "cosmos", place: WM("wikipedia/commons/thumb/4/46/NASA_logo_%282023_colors%29.svg/1280px-NASA_logo_%282023_colors%29.svg.png"), placeCaption: "Kennedy Space Center — her launch site",
    portrait: WM("wikipedia/commons/thumb/5/55/Mae_Carol_Jemison.jpg/960px-Mae_Carol_Jemison.jpg"),
    quote: "Never limit yourself because of others' limited imagination.",
    legacy: "The first Black woman to travel to space, aboard Endeavour in 1992." },
  { name: "Jacques Cousteau", years: "1910–1997", emoji: "🌊", scene: "ocean", place: WM("wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/1280px-Flag_of_Monaco.svg.png"), placeCaption: "Monaco — home of the Oceanographic Museum he directed",
    portrait: WM("wikipedia/commons/1/10/Cousteau1972_%28cropped%29.jpg"),
    quote: "The sea, once it casts its spell, holds one in its net of wonder forever.",
    legacy: "Co-invented the Aqua-Lung and brought the ocean's depths to television audiences worldwide." },
  { name: "Freya Stark", years: "1893–1993", emoji: "🐫", scene: "mountain", place: WM("wikipedia/commons/thumb/e/e7/Asolo-Nov-2021jpg_%283%29.jpg/1280px-Asolo-Nov-2021jpg_%283%29.jpg"), placeCaption: "Asolo, Italy — where she made her home",
    portrait: WM("wikipedia/commons/thumb/e/e9/Dame_Freya_Madeline_Stark_%281923%29.jpg/960px-Dame_Freya_Madeline_Stark_%281923%29.jpg"),
    quote: "To awaken quite alone in a strange town is one of the pleasantest sensations in the world.",
    legacy: "One of the first Western women to travel through the Arabian deserts alone." },
  { name: "Junko Tabei", years: "1939–2016", emoji: "🏔️", scene: "mountain", place: WM("wikipedia/commons/thumb/1/15/Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg/1280px-Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg"), placeCaption: "Mount Everest — the summit she was first to reach",
    portrait: WM("wikipedia/commons/5/57/Junko_Tabei_85_%283to4%29.jpg"),
    quote: "Do not give up. Keep on your quest.",
    legacy: "The first woman to summit Mount Everest, in 1975." },
  { name: "David Livingstone", years: "1813–1873", emoji: "🌍", scene: "mountain", place: WM("wikipedia/commons/thumb/d/da/Cataratas_Victoria%2C_Zambia-Zimbabue%2C_2018-07-27%2C_DD_04.jpg/1280px-Cataratas_Victoria%2C_Zambia-Zimbabue%2C_2018-07-27%2C_DD_04.jpg"), placeCaption: "Victoria Falls — which he named and made famous",
    portrait: WM("wikipedia/commons/thumb/f/f2/David_Livingstone_by_Thomas_Annan.jpg/960px-David_Livingstone_by_Thomas_Annan.jpg"),
    quote: "I am prepared to go anywhere, provided it be forward.",
    legacy: "His expeditions mapped much of central Africa's interior for European geography." },

  // ── Mathematics ──────────────────────────────────────────────────────
  { name: "Pythagoras", years: "c.570–495 BC", emoji: "📐", scene: "chalkboard", place: WM("wikipedia/commons/thumb/4/4b/Samos_049_2009.JPG/1280px-Samos_049_2009.JPG"), placeCaption: "Samos, Greece — his birthplace",
    portrait: WM("wikipedia/commons/thumb/e/e0/Pythagoras_in_the_Roman_Forum%2C_Colosseum.jpg/960px-Pythagoras_in_the_Roman_Forum%2C_Colosseum.jpg"),
    quote: "There is geometry in the humming of the strings.",
    legacy: "His theorem on right triangles remains foundational to mathematics and physics." },
  { name: "Euclid", years: "c.300 BC", emoji: "📏", scene: "chalkboard", place: WM("wikipedia/commons/thumb/7/79/San_Stefano_Grand_Plaza.JPG/1280px-San_Stefano_Grand_Plaza.JPG"), placeCaption: "Alexandria — home of the great library where he taught",
    portrait: WM("wikipedia/commons/thumb/7/73/Italian_-_Euclid_-_Google_Art_Project.jpg/960px-Italian_-_Euclid_-_Google_Art_Project.jpg"),
    quote: "Give him three pence, since he must make gain out of what he learns.",
    legacy: "Wrote Elements, the geometry textbook that shaped math education for over two millennia." },
  { name: "Archimedes", years: "c.287–212 BC", emoji: "🛁", scene: "chalkboard", place: WM("wikipedia/commons/3/34/Veduta_aerea_di_Siracusa_e_con_l%27Etna_sullo_sfondo_%28Foto_di_Angelo_Bonomo%29.jpg"), placeCaption: "Syracuse, Sicily — his home city",
    portrait: WM("wikipedia/commons/thumb/e/e7/Domenico-Fetti_Archimedes_1620.jpg/960px-Domenico-Fetti_Archimedes_1620.jpg"),
    quote: "Give me a place to stand, and I shall move the world.",
    legacy: "Discovered principles of buoyancy and leverage that underpin classical physics." },
  { name: "Alan Turing", years: "1912–1954", emoji: "💻", scene: "chalkboard", place: WM("wikipedia/commons/thumb/4/43/Bletchley_Park_Mansion.jpg/1280px-Bletchley_Park_Mansion.jpg"), placeCaption: "Bletchley Park — where he helped break the Enigma code",
    portrait: WM("wikipedia/commons/c/ce/Alan_turing_header.jpg"),
    quote: "Sometimes it is the people no one imagines anything of who do the things that no one can imagine.",
    legacy: "Laid the theoretical foundation for computer science and helped break the Enigma code." },
  { name: "Emmy Noether", years: "1882–1935", emoji: "🔢", scene: "chalkboard", place: WM("wikipedia/commons/thumb/8/8a/Goettingen_Marktplatz_Oct06_Antilived.jpg/1280px-Goettingen_Marktplatz_Oct06_Antilived.jpg"), placeCaption: "Göttingen — where she reshaped modern algebra",
    portrait: WM("wikipedia/commons/thumb/b/b5/Emmy_Noether_%283x4_cropped%29.jpg/960px-Emmy_Noether_%283x4_cropped%29.jpg"),
    quote: "My methods are really methods of working and thinking; this is why they have crept in everywhere anonymously.",
    legacy: "Her theorem linking symmetry and conservation laws reshaped modern physics." },
  { name: "Carl Friedrich Gauss", years: "1777–1855", emoji: "🔢", scene: "chalkboard", place: WM("wikipedia/commons/thumb/8/8a/Goettingen_Marktplatz_Oct06_Antilived.jpg/1280px-Goettingen_Marktplatz_Oct06_Antilived.jpg"), placeCaption: "Göttingen — his university and lifelong home",
    portrait: WM("wikipedia/commons/thumb/e/ec/Carl_Friedrich_Gauss_1840_by_Jensen.jpg/960px-Carl_Friedrich_Gauss_1840_by_Jensen.jpg"),
    quote: "Mathematics is the queen of the sciences.",
    legacy: "Contributed foundational work across number theory, statistics, and geometry." },
  { name: "Srinivasa Ramanujan", years: "1887–1920", emoji: "📓", scene: "chalkboard", place: WM("wikipedia/commons/3/3c/Kumbakonam_Mahamaham_Tank.jpg"), placeCaption: "Kumbakonam, India — his hometown",
    portrait: WM("wikipedia/commons/thumb/d/d0/Srinivasa_Ramanujan-Add._MS_a94_version2_%28cropped%29.jpg/960px-Srinivasa_Ramanujan-Add._MS_a94_version2_%28cropped%29.jpg"),
    quote: "An equation for me has no meaning unless it expresses a thought of God.",
    legacy: "A self-taught genius whose formulas continue to influence modern mathematics." },
  { name: "John von Neumann", years: "1903–1957", emoji: "🧮", scene: "chalkboard", place: WM("wikipedia/commons/thumb/b/ba/Princeton%2C_New_Jersey_%2855144921890%29.jpg/1280px-Princeton%2C_New_Jersey_%2855144921890%29.jpg"), placeCaption: "Princeton — home of the Institute for Advanced Study",
    portrait: WM("wikipedia/commons/5/5e/JohnvonNeumann-LosAlamos.gif"),
    quote: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.",
    legacy: "Contributed foundational work to computing, game theory, and quantum mechanics." },
  { name: "Katherine Johnson", years: "1918–2020", emoji: "🚀", scene: "cosmos", place: WM("wikipedia/commons/thumb/4/46/NASA_logo_%282023_colors%29.svg/1280px-NASA_logo_%282023_colors%29.svg.png"), placeCaption: "NASA Langley Research Center — where she calculated spaceflight trajectories",
    portrait: WM("wikipedia/commons/thumb/6/6d/Katherine_Johnson_1983.jpg/960px-Katherine_Johnson_1983.jpg"),
    quote: "Girls are capable of doing everything men are capable of doing. Sometimes they have more imagination than men.",
    legacy: "Her orbital mechanics calculations were critical to NASA's early crewed spaceflights." },
  { name: "Blaise Pascal", years: "1623–1662", emoji: "📐", scene: "chalkboard", place: WM("wikipedia/commons/c/c9/Ville_de_Clermont-Ferrand.jpg"), placeCaption: "Clermont-Ferrand — his birthplace",
    portrait: WM("wikipedia/commons/thumb/9/98/Blaise_Pascal_Versailles.JPG/960px-Blaise_Pascal_Versailles.JPG"),
    quote: "The heart has its reasons which reason knows nothing of.",
    legacy: "Founded probability theory and built one of the first mechanical calculators." },
  { name: "Hypatia", years: "c.360–415", emoji: "📚", scene: "library", place: WM("wikipedia/commons/thumb/7/79/San_Stefano_Grand_Plaza.JPG/1280px-San_Stefano_Grand_Plaza.JPG"), placeCaption: "Alexandria — the ancient world’s center of learning", portrait: "",
    quote: "Reserve your right to think, for even to think wrongly is better than not to think at all.",
    legacy: "One of the last great scholars of ancient Alexandria, teaching mathematics and philosophy." },
  { name: "Leonhard Euler", years: "1707–1783", emoji: "🔢", scene: "chalkboard", place: WM("wikipedia/commons/thumb/f/f5/Basel_-_M%C3%BCnsterpfalz1.jpg/1280px-Basel_-_M%C3%BCnsterpfalz1.jpg"), placeCaption: "Basel, Switzerland — his birthplace",
    portrait: WM("wikipedia/commons/thumb/f/f9/Leonhard_Euler_-_Jakob_Emanuel_Handmann_%28Kunstmuseum_Basel%29.jpg/960px-Leonhard_Euler_-_Jakob_Emanuel_Handmann_%28Kunstmuseum_Basel%29.jpg"),
    quote: "Logic is the foundation of the certainty of all the knowledge we acquire.",
    legacy: "Among history's most prolific mathematicians, shaping notation still used today." },

  // ── Film & performing arts ───────────────────────────────────────────
  { name: "Charlie Chaplin", years: "1889–1977", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/b/bd/Kennington_Park_-_geograph.org.uk_-_1009307.jpg"), placeCaption: "Kennington, London — his birthplace",
    portrait: WM("wikipedia/commons/thumb/8/82/Charlie_Chaplin_portrait_Getty_1739411952.jpg/960px-Charlie_Chaplin_portrait_Getty_1739411952.jpg"),
    quote: "A day without laughter is a day wasted.",
    legacy: "Silent film's greatest star, writing, directing, and scoring his own movies." },
  { name: "Audrey Hepburn", years: "1929–1993", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/a/ae/Grand_Place_Bruselas_2.jpg/1280px-Grand_Place_Bruselas_2.jpg"), placeCaption: "Brussels — her birthplace",
    portrait: WM("wikipedia/commons/thumb/7/74/AudreyKHepburn.jpg/960px-AudreyKHepburn.jpg"),
    quote: "Nothing is impossible, the word itself says 'I'm possible'!",
    legacy: "An Oscar-winning actress who became equally renowned for humanitarian work with UNICEF." },
  { name: "Alfred Hitchcock", years: "1899–1980", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/9/98/Leytonstone_High_Road_Christmas_lights%2C_London%2C_England_03.jpg/1280px-Leytonstone_High_Road_Christmas_lights%2C_London%2C_England_03.jpg"), placeCaption: "Leytonstone, London — his birthplace",
    portrait: WM("wikipedia/commons/9/94/Hitchcock%2C_Alfred_02.jpg"),
    quote: "There is no terror in the bang, only in the anticipation of it.",
    legacy: "The 'Master of Suspense' redefined the thriller across a 50-film career." },
  { name: "Katharine Hepburn", years: "1907–2003", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/a/a8/Hartford%2C_CT_skyline_%28cropped%29.jpg/1280px-Hartford%2C_CT_skyline_%28cropped%29.jpg"), placeCaption: "Hartford, Connecticut — her birthplace",
    portrait: WM("wikipedia/commons/thumb/8/89/Katharine_Hepburn_publicity_photograph.jpg/960px-Katharine_Hepburn_publicity_photograph.jpg"),
    quote: "If you obey all the rules, you miss all the fun.",
    legacy: "Won a record four Academy Awards for Best Actress across six decades." },
  { name: "Akira Kurosawa", years: "1910–1998", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg"), placeCaption: "Tokyo — his birthplace and home",
    portrait: WM("wikipedia/commons/thumb/4/48/Akirakurosawa-onthesetof7samurai-1953-page88.jpg/960px-Akirakurosawa-onthesetof7samurai-1953-page88.jpg"),
    quote: "In a mad world, only the mad are sane.",
    legacy: "His films, from Rashomon to Seven Samurai, reshaped world cinema." },
  { name: "Meryl Streep", years: "1949–", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/3/37/SummitDowntownSep.jpg/1280px-SummitDowntownSep.jpg"), placeCaption: "Summit, New Jersey — her birthplace",
    portrait: WM("wikipedia/commons/thumb/e/e5/Meryl_Streep-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194765350_%28cropped1%29.jpg/960px-Meryl_Streep-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194765350_%28cropped1%29.jpg"),
    quote: "The great gift of human beings is that we have the power of empathy.",
    legacy: "Holds the record for the most Academy Award acting nominations." },
  { name: "Ingmar Bergman", years: "1918–2007", emoji: "🎬", scene: "curtain",
    portrait: WM("wikipedia/commons/f/f2/Ingmar_Bergman_%281966%29.jpg"),
    quote: "Film as dream, film as music. No form of art goes beyond ordinary consciousness as film does.",
    legacy: "His introspective films made him one of cinema's most influential directors." },
  { name: "Sidney Poitier", years: "1927–2022", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/8/88/Nassau%2C_Bahamas_aerial_view_%28cropped%29.jpg/1280px-Nassau%2C_Bahamas_aerial_view_%28cropped%29.jpg"), placeCaption: "Nassau, the Bahamas — his childhood home",
    portrait: WM("wikipedia/commons/2/29/Sidney_Poitier_1968.jpg"),
    quote: "I was very well trained by my mother and father, and my values are quite deeply ingrained in me.",
    legacy: "The first Black actor to win the Academy Award for Best Actor, in 1964." },
  { name: "Marlon Brando", years: "1924–2004", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/b/b6/City_of_Omaha%2C_Nebraska_Skyline_on_the_Missouri_River_%2830899969517%29.jpg/1280px-City_of_Omaha%2C_Nebraska_Skyline_on_the_Missouri_River_%2830899969517%29.jpg"), placeCaption: "Omaha, Nebraska — his birthplace",
    portrait: WM("wikipedia/commons/thumb/5/53/Marlon_Brando_publicity_for_One-Eyed_Jacks.png/960px-Marlon_Brando_publicity_for_One-Eyed_Jacks.png"),
    quote: "An actor's a guy who, if you ain't talking about him, ain't listening.",
    legacy: "Redefined screen acting with a raw, naturalistic style in On the Waterfront and beyond." },
  { name: "Satyajit Ray", years: "1921–1992", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/d/d7/Kolkata_maidan.jpg/1280px-Kolkata_maidan.jpg"), placeCaption: "Kolkata — his home city",
    portrait: WM("wikipedia/commons/d/dc/Satyajit_Ray_in_New_York_%28cropped%29.jpg"),
    quote: "What is important is that one must have a point of view, and one must be honest to oneself, in terms of that point of view.",
    legacy: "The Apu Trilogy established Indian cinema on the world stage." },
  { name: "Elizabeth Taylor", years: "1932–2011", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/5/5d/Hampstead_047.jpg/1280px-Hampstead_047.jpg"), placeCaption: "Hampstead, London — her birthplace",
    portrait: WM("wikipedia/commons/thumb/8/8e/Taylor%2C_Elizabeth_posed.jpg/960px-Taylor%2C_Elizabeth_posed.jpg"),
    quote: "I've been through it all, baby, I'm mother courage.",
    legacy: "A two-time Oscar winner who became one of Hollywood's first modern celebrities." },
  { name: "Stanley Kubrick", years: "1928–1999", emoji: "🎬", scene: "curtain", place: WM("wikipedia/commons/thumb/a/ad/New_York_Botanical_Garden_April_2015_010.jpg/1280px-New_York_Botanical_Garden_April_2015_010.jpg"), placeCaption: "the Bronx, New York — his birthplace",
    portrait: WM("wikipedia/commons/thumb/5/59/Stanley_Kubrick_in_Dr._Strangelove_Trailer_%284%29_Cropped.jpg/960px-Stanley_Kubrick_in_Dr._Strangelove_Trailer_%284%29_Cropped.jpg"),
    quote: "The most terrifying fact about the universe is not that it is hostile but that it is indifferent.",
    legacy: "Obsessive craftsmanship across genres made him one of film's most influential directors." },
  { name: "Gene Kelly", years: "1912–1996", emoji: "💃", scene: "curtain", place: WM("wikipedia/commons/thumb/d/d6/Ascending_the_Duquesne_Incline.jpg/1280px-Ascending_the_Duquesne_Incline.jpg"), placeCaption: "Pittsburgh — his hometown",
    portrait: WM("wikipedia/commons/thumb/3/31/Committee_for_Free_Spain._Portrait_of_M._Woolf_and_Jack_%28possibly_Captain_Jack_White%29_Taken_for_the_Committee._%28Includes_photo_of_film_star_Gene_Kelly%29._Sep_1946_Slide_2_Trim_Edit.png/960px-thumbnail.png"),
    quote: "The idea of dance as something that a real man could do simply hadn't occurred to most Americans.",
    legacy: "Reinvented the movie musical by bringing athletic, balletic dance to the screen." },
  { name: "Josephine Baker", years: "1906–1975", emoji: "💃", scene: "concert", place: WM("wikipedia/en/thumb/9/93/Folies_Bergere_after_renovatation_of_facade_2013.jpg/1280px-Folies_Bergere_after_renovatation_of_facade_2013.jpg"), placeCaption: "the Folies Bergère, Paris — where she became a sensation",
    portrait: WM("wikipedia/commons/0/0b/Baker_Harcourt_1940_2.jpg"),
    quote: "I was a devil in other countries, and I was a little devil in America too.",
    legacy: "A trailblazing entertainer and French Resistance agent who broke racial barriers on stage." },
];

export const FIGURES: Figure[] = RAW.map((f) => ({
  name: f.name,
  years: f.years,
  emoji: f.emoji,
  portrait: f.portrait,
  scene: f.place ? f.placeCaption! : SCENES[f.scene].label,
  sceneImg: f.place || SCENES[f.scene].img,
  scenePersonal: Boolean(f.place),
  quote: f.quote,
  legacy: f.legacy,
}));

/** Deterministic daily index (UTC day count) so server and client agree on first render. */
export function dailyFigureIndex(epochMs: number): number {
  return Math.floor(epochMs / 86400000) % FIGURES.length;
}
